# Generated by Django 5.2.5 on 2026-01-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dbg', models.IntegerField(unique=True, verbose_name='id_DBG')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование группы')),
                ('nameFull', models.CharField(max_length=150, verbose_name='Полное наименование группы')),
                ('name2', models.CharField(max_length=50, verbose_name='Наименование группы вар2')),
                ('is_active', models.BooleanField(default=False)),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sklad_pro.dbg', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['-id'],
            },
        ),
    ]
