# Generated by Django 5.2.5 on 2026-02-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad_pro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbg',
            name='id_dbg',
            field=models.IntegerField(blank=True, unique=True, verbose_name='id_DBG'),
        ),
        migrations.AlterField(
            model_name='dbg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dbg',
            name='name2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование группы вар2'),
        ),
        migrations.AlterField(
            model_name='dbg',
            name='nameFull',
            field=models.CharField(blank=True, max_length=150, verbose_name='Полное наименование группы'),
        ),
    ]
